# Generated by Django 4.2.1 on 2023-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotquotes', '0002_alter_actor_quoter_alter_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='quoter',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=5000),
        ),
    ]
